### ISSUE TITLE
Individual archives should render child posts

### ISSUE THREAD

**Issue by bowserm** [Shazwazza/Articulate#304] opened 2019-05-02 22:57 UTC
This issue is related to this resolved issue:

- [Allow multiple archive nodes under an Articulate root #9](https://github.com/Shazwazza/Articulate/issues/9)
- https://our.umbraco.com/packages/starter-kits/articulate/discussions/54492-Enable-multiple-archives

When I create multiple archives, all of their posts are correctly aggregated under the root Articulate node correctly after issue #9 . However, each of the individual archives 404 when they aren't configured to redirect to the root, so I am unable to see only the posts that belong to a specific category.

**Comment by Shazwazza** [comment] 2019-05-02 23:38
I'm not fully understanding what the issue is and what this PR resolves. Sorry but It's been a very long time since i looked at that old forum post.

Can you provide steps to reproduce the problem? And then steps for testing this PR?

**Comment by bowserm** [comment] 2019-05-03 00:06
Sorry about that. I have a content structure that looks like this:

 - Home
   - Blog
     - Archive 1
     - Archive 2
     - Archive 3
     - ...
  - Contact Us
  - ...

When I render the /blog page, I get an aggregate of all of the blog articles. I can even configure the archive nodes to redirect to the root blog using the `Redirect Archive` setting. This is also great. However, when I try to render `/blog/archive-1` when `Redirect Archive` is false, I get a 404 instead of seeing only the blog articles related to `Archive 1`.

Steps to reproduce:
 1. Create multiple articulate archives under the articulate root node
 1. Create at least one article under each archive for testing purposes.
 1. Set `Redirect Archive` to `false` on the articulate root node under the `Customize` tab
 1. View the blog root at /blog. You should see an aggregated list of all of the blog articles
 1. View a few of the individual archives at `/blog/archive-1`, `/blog/archive-2`, etc..

**Actual:**
The archive pages 404

**Expected:**
The archive pages render the same as the blog root using the `App_Plugins/Articulate/Themes/<your theme>/Views/List.cshtml` but they only render their child blog articles.

**Comment by Shazwazza** [comment] 2019-05-03 00:33
Ah i see thanks for that. This would be a new feature essentially since currently the actual Archive node has never rendered anything and as you pointed out just returns a 404 but i can see it's usefulness!

I'm trying to get Articulate 4.0.0 out (based on umb v8) so will need to revisit this once that is done.

**Comment by Shazwazza** [comment] 2020-01-31 00:41
Have marked as help wanted (up for grabs) if anyone feels like giving this a try

**Closed** 2020-09-21 13:16 UTC
Labels: enhancement, help wanted

**Comment by Shazwazza** [comment] 2020-12-16 23:43
@bowserm + @frederiktoft 

Have fixed up code and pushed, all working as expected :) will get next version out soon. Thanks for the effort and sorry for the delay.

For now the feature will really only be implemented if people manually implement it and disable the archive redirect but I think that's ok for now. If you feel like any of the default themes could/should use this feature please let me know how you think that should work and we can make a task to enable showcasing it as part of a theme.

I'll get a new version out shortly.
