### ISSUE TITLE
404 on /blog (i.e. the ArticulateArchive page)

### ISSUE THREAD

**Issue by MusicDemon** [Shazwazza/Articulate#213] opened 2017-02-08 21:04 UTC
In reference to #85.

The issue is present and as I posted there, your page also suffers from this issue.
Would you be so kind to open the issue back up?

**Comment by Shazwazza** [comment] 2017-03-20 01:55
To be clear about this particular issue - it's the ArticulateArchive node page that returns a 404. The reason for this is because there is no template assigned to the ArticulateArchive document type. This was by design because this content node acts as a container for blog posts but the root Articulate node cannot be the container for blog posts because it must contain other content nodes for things like Authors, (and maybe others in the future)

In theory, there's would be no links to this page unless someone manually navigates to it, but we can easily put in a fix that will permanently redirect this page to the blog root. 

For example:

* www.mysite.com/en/blogs/myblog/archive/post-1 
   * This would be a blog post
* www.mysite.com/en/blogs/myblog/archive
   * This would return a 404 but a user would only get this if they manually navigated to it
   * The simple fix would be to 301 redirect this to the blog root; www.mysite.com/en/blogs/myblog

Alternatively, the special umbraco fields could be added to this doc type https://our.umbraco.org/documentation/Reference/Routing/routing-properties 
and you could redirect/rewrite anywhere you want. Or if you wanted, you could add a template to this page and render anything that you'd like (but that's not something that will ever be OOTB with Articulate)

**Comment by Shazwazza** [comment] 2017-03-20 02:29
There's now a redirectArchive property type on the blog root node and when that is enabled it will perform the 301 redirection.

**Closed by Shazwazza** 2017-03-20 02:29 UTC
