### ISSUE TITLE
Tags and Categories disappear for already published posts

### ISSUE THREAD

**Issue by bobi33** [Shazwazza/Articulate#230] opened 2017-04-26 20:22 UTC
Hi,

Tags and Categories disappear for already published posts while making changes to the Articulate (i.e. moving Articulate into another node, or making it a root node).

**Comment by Shazwazza** [comment] 2017-06-22 13:35
Is this due to the small amount of caching that occurs for categories/tags? Does it still do this if you have compilation debug="true in your web.config ?

**Comment by philius44** [comment] 2017-08-28 10:44
just seen that my issue post https://github.com/Shazwazza/Articulate/issues/268 is a duplicate of this. Yes, I have debug=true in my web.config and the issue is still there.

**Comment by Shazwazza** [comment] 2020-02-03 13:24
closing as duplicate of #268

**Closed by Shazwazza** 2020-02-03 13:24 UTC
