### ISSUE TITLE
Markdown editor links - https and links with multiple works

### ISSUE THREAD

**Issue by rustyswayne** [Shazwazza/Articulate#90] opened 2015-07-11 03:20 UTC
Hey there Shannon - I've been futzing quite a bit with Articulate and have noticed that in the Markdown editor links created with https never render and depending on the order at which one puts in (as in sometimes I go back and add links) that have multiple words like "[Multiple Words][4]" they will not actually render as links albeit the pattern saves correctly with   [4]: http://somewhere.com/ 

However, if there is only a single link in the content multiple words seems to work fine but https links do not.

**Comment by Shazwazza** [comment] 2015-07-13 07:40
hrm, so the issue is just when running in https ?

**Comment by rustyswayne** [comment] 2015-07-15 12:34
I think there are two issues, potentially related. 

 1. Using https in a link will not work.  Changing the link to http and hoping the endpoint handles the switch has been my only option.
 2. I've had issues creating links with multiple words in the anchor text.  I need to go back and test to see if it is only after I've tried to add a link with https.  However, I do know that whatever the trigger is, once it happens the only way I could get the link to stick is to wrap a single word in the anchor - e.g. change "FirstName LastName" to "FirstName"

**Comment by Shazwazza** [comment] 2018-08-15 03:08
I know this has taken far too long for me to get to testing this, really sorry about that. I've tested all of the above in the latest Articulate and it all seems to work as expected. I'll close this issue.

**Closed by Shazwazza** 2018-08-15 03:08 UTC
